#!/bin/bash
# -*- ENCODING: UTF-8 -*-
cp  -r /home/chavalinan/Chava/e08rcl/s08006 /home/chavalinan/CuencaConchos/Ic
cp  -r /home/chavalinan/Chava/e08rcl/s08318 /home/chavalinan/CuencaConchos/Ig
cp  -r /home/chavalinan/Chava/e08rcl/s08213 /home/chavalinan/CuencaConchos/Ig
cp  -r /home/chavalinan/Chava/e08rcl/s08283 /home/chavalinan/CuencaConchos/Ig
cp  -r /home/chavalinan/Chava/e08rcl/s08030 /home/chavalinan/CuencaConchos/Ig
cp  -r /home/chavalinan/Chava/e08rcl/s08051 /home/chavalinan/CuencaConchos/Ja
cp  -r /home/chavalinan/Chava/e08rcl/s08241 /home/chavalinan/CuencaConchos/Ja
cp  -r /home/chavalinan/Chava/e08rcl/s08316 /home/chavalinan/CuencaConchos/Ja
cp  -r /home/chavalinan/Chava/e08rcl/s08031 /home/chavalinan/CuencaConchos/Ja
cp  -r /home/chavalinan/Chava/e08rcl/s08072 /home/chavalinan/CuencaConchos/Jb 
cp  -r /home/chavalinan/Chava/e08rcl/s08189 /home/chavalinan/CuencaConchos/Jb 
cp  -r /home/chavalinan/Chava/e08rcl/s08039 /home/chavalinan/CuencaConchos/Jb 
cp  -r /home/chavalinan/Chava/e08rcl/s08247 /home/chavalinan/CuencaConchos/Jb
cp  -r /home/chavalinan/Chava/e08rcl/s08037 /home/chavalinan/CuencaConchos/Jb
cp  -r /home/chavalinan/Chava/e08rcl/s08180 /home/chavalinan/CuencaConchos/Jc 
cp  -r /home/chavalinan/Chava/e08rcl/s08049 /home/chavalinan/CuencaConchos/Ka
cp  -r /home/chavalinan/Chava/e08rcl/s08311 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08013 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08162 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08135 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08187 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08300 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08083 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08092 /home/chavalinan/CuencaConchos/Kb
cp  -r /home/chavalinan/Chava/e08rcl/s08251 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08113 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08185 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08056 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08002 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08114 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08165 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08212 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08109 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08040 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08112 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08337 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08323 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08303 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08147 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08270 /home/chavalinan/CuencaConchos/Kc
cp  -r /home/chavalinan/Chava/e08rcl/s08040 /home/chavalinan/CuencaConchos/Kd
cp  -r /home/chavalinan/Chava/e08rcl/s08274 /home/chavalinan/CuencaConchos/Kd
cp  -r /home/chavalinan/Chava/e08rcl/s08306 /home/chavalinan/CuencaConchos/La
cp  -r /home/chavalinan/Chava/e08rcl/s08085 /home/chavalinan/CuencaConchos/La
cp  -r /home/chavalinan/Chava/e08rcl/s08153 /home/chavalinan/CuencaConchos/Lb
cp  -r /home/chavalinan/Chava/e08rcl/s08152 /home/chavalinan/CuencaConchos/Lb
cp  -r /home/chavalinan/Chava/e08rcl/s08137 /home/chavalinan/CuencaConchos/Lc
cp  -r /home/chavalinan/Chava/e08rcl/s08021 /home/chavalinan/CuencaConchos/Lc
cp  -r /home/chavalinan/Chava/e08rcl/s08319 /home/chavalinan/CuencaConchos/Ld
cp  -r /home/chavalinan/Chava/e08rcl/s08183 /home/chavalinan/CuencaConchos/Le
cp  -r /home/chavalinan/Chava/e08rcl/s08105 /home/chavalinan/CuencaConchos/Le
cp  -r /home/chavalinan/Chava/e08rcl/s08060 /home/chavalinan/CuencaConchos/Lf
cp  -r /home/chavalinan/Chava/e08rcl/s08169 /home/chavalinan/CuencaConchos/Lf
cp  -r /home/chavalinan/Chava/e08rcl/s08327 /home/chavalinan/CuencaConchos/Lf
cp  -r /home/chavalinan/Chava/e08rcl/s08061 /home/chavalinan/CuencaConchos/Lg
cp  -r /home/chavalinan/Chava/e08rcl/s08267 /home/chavalinan/CuencaConchos/Lg
cp  -r /home/chavalinan/Chava/e08rcl/s08322 /home/chavalinan/CuencaConchos/Lg
cp  -r /home/chavalinan/Chava/e08rcl/s08320 /home/chavalinan/CuencaConchos/Lg
cp  -r /home/chavalinan/Chava/e08rcl/s08005 /home/chavalinan/CuencaConchos/Lg
cp  -r /home/chavalinan/Chava/e08rcl/s08133 /home/chavalinan/CuencaConchos/Ma
cp  -r /home/chavalinan/Chava/e08rcl/s08025 /home/chavalinan/CuencaConchos/Ma
cp  -r /home/chavalinan/Chava/e08rcl/s08250 /home/chavalinan/CuencaConchos/Ma
cp  -r /home/chavalinan/Chava/e08rcl/s08081 /home/chavalinan/CuencaConchos/Ma
cp  -r /home/chavalinan/Chava/e08rcl/s08029 /home/chavalinan/CuencaConchos/Ma
cp  -r /home/chavalinan/Chava/e08rcl/s08186 /home/chavalinan/CuencaConchos/Mb
cp  -r /home/chavalinan/Chava/e08rcl/s08156 /home/chavalinan/CuencaConchos/Mb
cp  -r /home/chavalinan/Chava/e08rcl/s08317 /home/chavalinan/CuencaConchos/Mb
cp  -r /home/chavalinan/Chava/e08rcl/s08194 /home/chavalinan/CuencaConchos/Mb
cp  -r /home/chavalinan/Chava/e08rcl/s08257 /home/chavalinan/CuencaConchos/Mb
cp  -r /home/chavalinan/Chava/e10rcl/s10062 /home/chavalinan/CuencaConchos/Mc
cp  -r /home/chavalinan/Chava/e10rcl/s10173 /home/chavalinan/CuencaConchos/Mc
cp  -r /home/chavalinan/Chava/e08rcl/s08314 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08054 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08273 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08078 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08305 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08011 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08033 /home/chavalinan/CuencaConchos/Md
cp  -r /home/chavalinan/Chava/e08rcl/s08151 /home/chavalinan/CuencaConchos/Me
cp  -r /home/chavalinan/Chava/e08rcl/s08260 /home/chavalinan/CuencaConchos/Me
cp  -r /home/chavalinan/Chava/e08rcl/s08130 /home/chavalinan/CuencaConchos/Me
cp  -r /home/chavalinan/Chava/e08rcl/s08199 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08174 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08202 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08014 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08304 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08044 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08027 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08120 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08102 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08019 /home/chavalinan/CuencaConchos/Na
cp  -r /home/chavalinan/Chava/e08rcl/s08050 /home/chavalinan/CuencaConchos/Nc
cp  -r /home/chavalinan/Chava/e08rcl/s08196 /home/chavalinan/CuencaConchos/Nc
cp  -r /home/chavalinan/Chava/e08rcl/s08123 /home/chavalinan/CuencaConchos/Nc
cp  -r /home/chavalinan/Chava/e08rcl/s08088 /home/chavalinan/CuencaConchos/Nc
cp  -r /home/chavalinan/Chava/e08rcl/s08188 /home/chavalinan/CuencaConchos/Nc
cp  -r /home/chavalinan/Chava/e08rcl/s08158 /home/chavalinan/CuencaConchos/Nc
cp  -r /home/chavalinan/Chava/e08rcl/s08175 /home/chavalinan/CuencaConchos/Nd
cp  -r /home/chavalinan/Chava/e08rcl/s08099 /home/chavalinan/CuencaConchos/Nd
cp  -r /home/chavalinan/Chava/e08rcl/s08136 /home/chavalinan/CuencaConchos/Ne
cp  -r /home/chavalinan/Chava/e08rcl/s08310 /home/chavalinan/CuencaConchos/Ne
cp  -r /home/chavalinan/Chava/e08rcl/s08331 /home/chavalinan/CuencaConchos/Ne
cp  -r /home/chavalinan/Chava/e08rcl/s08127 /home/chavalinan/CuencaConchos/Ne
cp  -r /home/chavalinan/Chava/e08rcl/s08009 /home/chavalinan/CuencaConchos/Ne
exit 

